name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create firebase credentials file
        run: echo '${{ secrets.FIREBASE_TOKEN }}' > /tmp/firebase-key.json

      - name: Authenticate with Firebase
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-key.json
          firebase deploy --project controle-atividade-a6b6d
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-key.json
